// <auto-generated />
using System;
using EmployeeApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeApi.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260717183317_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DesignationEmployee", b =>
                {
                    b.Property<int>("DesignationsDesignationId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeesEmployeeId")
                        .HasColumnType("int");

                    b.HasKey("DesignationsDesignationId", "EmployeesEmployeeId");

                    b.HasIndex("EmployeesEmployeeId");

                    b.ToTable("DesignationEmployee");
                });

            modelBuilder.Entity("EmployeeApi.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "Human Resources (HR)",
                            Description = "Handles employee recruitment, training, attendance, payroll, and employee welfare."
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "Information Technology (IT)",
                            Description = "Manages software development, hardware maintenance, networks, and technical support."
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "Accounts & Finance",
                            Description = "Responsible for accounting, budgeting, financial reporting, and payment management."
                        },
                        new
                        {
                            DepartmentId = 4,
                            DepartmentName = "Sales",
                            Description = "Manages customer relationships, quotations, sales orders, and revenue generation."
                        },
                        new
                        {
                            DepartmentId = 5,
                            DepartmentName = "Marketing",
                            Description = "Promotes products, manages branding, advertising, and market research."
                        },
                        new
                        {
                            DepartmentId = 6,
                            DepartmentName = "Production",
                            Description = "Responsible for manufacturing products and managing production operations."
                        },
                        new
                        {
                            DepartmentId = 7,
                            DepartmentName = "Purchase",
                            Description = "Purchases raw materials, office supplies, and manages supplier relationships."
                        },
                        new
                        {
                            DepartmentId = 8,
                            DepartmentName = "Inventory / Store",
                            Description = "Maintains stock, warehouse operations, and inventory transactions."
                        },
                        new
                        {
                            DepartmentId = 9,
                            DepartmentName = "Quality Assurance (QA)",
                            Description = "Ensures product quality through inspection, testing, and quality control processes."
                        },
                        new
                        {
                            DepartmentId = 10,
                            DepartmentName = "Administration",
                            Description = "Oversees office administration, documentation, assets, and facility management."
                        });
                });

            modelBuilder.Entity("EmployeeApi.Models.Designation", b =>
                {
                    b.Property<int>("DesignationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DesignationId"));

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DesignationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.HasKey("DesignationId");

                    b.ToTable("Designations");
                });

            modelBuilder.Entity("EmployeeApi.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("DesignationEmployee", b =>
                {
                    b.HasOne("EmployeeApi.Models.Designation", null)
                        .WithMany()
                        .HasForeignKey("DesignationsDesignationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmployeeApi.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeesEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmployeeApi.Models.Employee", b =>
                {
                    b.HasOne("EmployeeApi.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EmployeeApi.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
